apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-generator
  template:
    metadata:
      labels:
        app: event-generator
    spec:
      containers:
        - name: event-generator
          image: localhost:5000/event-generator:test
          args: ["--config", "/config/config.toml"]
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: event-generator-config
            items:
              - key: config.toml
                path: config.toml
